### ISSUE TITLE
Need help with setting up package

### ISSUE THREAD

**Issue by ickyrr** [4commerce-technologies-AG/meteor-package-environments#3]
Hello, I installed this package and followed the instructions you provided, when I run the project, it works even on passenger and nginx. Here's my file structure:

```
private
----config
--------development
--------------public/startup.json
--------------server/startup.json
--------local
--------------public/startup.json
--------------server/startup.json
--------production
--------------public/startup.json
--------------server/startup.json
```

I thought everything was working fine but when I run the project, only the "development" folder is being read. Am I doing something wrong here? Any help would be appreciated, I'm still new on Meteor and all these environments so please take it easy. :)

**Comment by TomFreudenberg** [comment]
Hi @ickyrr 

thanks for using that piece of package, hopefully it is as useful to you as to us.

"Everything" works like expected because only ONE SET of settings are published when running your meteor app. WHAT SET is based on your NODE_ENV settings or per default = DEVELOPMENT.

So try starting meteor while also setting your environment var NODE_ENV

```
NODE_ENV=local meteor
```

or

```
NODE_ENV=production meteor
```

The first will read and push content of "local" folder and the second will do it for "production" server.

Just to clarify: this is defined as the feature and so you e.g. could define ONE SETTING like `my_smtp_server` inside the development environment as `localhost` but somewhere else as `192.168.178.1`.

You just need to change the ENV_VAR during meteor start for that changes and no changes are necessary to your code.

Cheers
Tom

**Comment by ickyrr** [comment]
Hi, sorry took me long to reply. Yep, it works alright! Thank you!
